title: Kevin Comaduran
#description: [A short description of your site's purpose]
#description : text below image
theme: jekll-theme-minimal
#plugins: pages-themes/minimal@v0.2.0
#gem "github-pages", group: :jekyll_plugins
