title: Kevin Comaduran
#description: [A short description of your site's purpose]
#description : text below image
theme: pages-themes/minimal@v0.2.0
#plugins: 
#gem "github-pages", group: :jekyll_plugins
#jekll-theme-minimal
